[build]
publish = "public"
command = "npm run build"
functions = "functions"

[[redirects]]
  from = "/admin"
  to = "/"
  status = 302

[[redirects]]
  from = "/buildr/*"
  to = "/.netlify/functions/auth"
  status = 200